apiVersion: apps/v1
kind: Deployment
metadata:
  name: connected-app
spec:
  selector:
    matchLabels:
      app: connected-city
  template:
    metadata:
      labels:
        app: connected-city
    spec:
      containers:
      - name: connected-app
        image: shantayya/connected-app:v1
        ports:
        - containerPort: 5000
      imagePullSecrets: 
      - name: dockersecret.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: connected-app
spec:
  selector:
    app: connected-city
  ports:
  - port: 80
    targetPort: 5000
  type: LoadBalancer


